// should similar to markdown syntax
// Copyright 2000-2022 JetBrains s.r.o. and other contributors. Use of this source code is governed by the Apache 2.0 license that can be found in the LICENSE file.
{
  parserClass="cc.unitmesh.language.parser.DevInParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="DevIn"
  psiImplClassSuffix="Impl"
  psiPackage="cc.unitmesh.language.psi"
  psiImplPackage="cc.unitmesh.language.psi.impl"

  elementTypeHolderClass="cc.unitmesh.language.psi.DevInTypes"
  elementTypeClass="cc.unitmesh.language.psi.DevInElementType"
  tokenTypeClass="cc.unitmesh.language.lexer.DevInTokenType"

  tokens=[
    AGENT_START        = "AGENT_START"
    COMMAND_START      = "COMMAND_START"
    VARIABLE_START     = "VARIABLE_START"
    CODE_BLOCK_START   = "CODE_BLOCK_START"
    CODE_BLOCK_END     = "CODE_BLOCK_END"
    CODE_BLOCK         = "CODE_BLOCK"
    CODE_CONTENT       = "CODE_CONTENT"
    IDENTIFIER         = "IDENTIFIER"
    LANGUAGE_ID        = "LANGUAGE_ID"
  ]
}

DevInFile ::= (used | code | TEXT_SEGMENT | NEWLINE)*

used ::= (
    AGENT_START AGENT_ID?
    | COMMAND_START COMMAND_ID?
    | VARIABLE_START VARIABLE_ID?
)

code ::=  CODE_BLOCK_START LANGUAGE_ID? code_contents CODE_BLOCK_END

code_contents ::= (NEWLINE | CODE_CONTENT)*