{
  parserClass="cc.unitmesh.devti.language.parser.SilveryParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Silvery"
  psiImplClassSuffix="Impl"
  psiPackage="cc.unitmesh.devti.language.psi"
  psiImplPackage="cc.unitmesh.devti.language.psi.impl"

  elementTypeHolderClass="cc.unitmesh.devti.language.psi.SilveryTypes"
  elementTypeClass="cc.unitmesh.devti.language.psi.SilveryElementType"
  tokenTypeClass="cc.unitmesh.devti.language.psi.SilveryTokenType"

  psiImplUtilClass="cc.unitmesh.devti.language.psi.impl.SilveryPsiImplUtil"
}

root ::= devtiUrl

devtiUrl ::= 'devti://' storyPath

storyPath ::= 'story' '/' source '/' storyId '/' acValues?

source ::= 'github'| 'jira' | 'trello'

storyId ::= integer

// Matches a comma-separated list of AC values enclosed in curly braces
acValues ::= '{' acValue (',' acValue)* '}'

// Define the rules for integer and ac_value
acValue ::= ('AC' INTEGER_LITERAL) {pin=2}
